/*
  BASE DE DATOS DE BLOG DE ANIME
*/

USE animeMG;
/* SET FOREIGN_KEY_CHECKS=0;   si es que se agregan las tablas mas de una vez */
/*SET FOREIGN_KEY_CHECKS=0;*/
ALTER DATABASE animeMG charset=utf8;


DROP TABLE IF EXISTS COOKIE_SESION;
DROP TABLE IF EXISTS RECUPERAR_CONTRASEÑA;
DROP TABLE IF EXISTS COMENTARIOS_USUARIOS;
DROP TABLE IF EXISTS VALORACIONES_USUARIOS;
DROP TABLE IF EXISTS VALORACIONES;
DROP TABLE IF EXISTS PUBLICACIONES;
DROP TABLE IF EXISTS COMENTARIO;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
  ID_USU   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE   VARCHAR(45) NOT NULL UNIQUE,
  PASS     VARCHAR(200) NOT NULL,
  EMAIL    VARCHAR(45) NOT NULL UNIQUE,
  IMAGEN   VARCHAR(200),
  ROL      VARCHAR(20)
);

CREATE TABLE COMENTARIO (
  ID_COM    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CONTENIDO VARCHAR(200) NOT NULL,
  FECHA     DATE NOT NULL
);

CREATE TABLE PUBLICACIONES(
  ID_PUBLI    INT AUTO_INCREMENT PRIMARY KEY,
  TITULO      VARCHAR(45),
  AUTOR       VARCHAR(45),
  IMAGEN      VARCHAR(200),
  DESCRIPCION VARCHAR(2000),
  CATEGORIA   VARCHAR(45)
);

CREATE TABLE VALORACIONES(
  ID_VAL     INT AUTO_INCREMENT PRIMARY KEY,
  PUNTUACION INT NOT NULL
);

CREATE TABLE VALORACIONES_USUARIOS(
  ID_VAL_USU           INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO_USUVAL    INT,
  ID_VALORACION_USUVAL INT,
  FOREIGN KEY (ID_USUARIO_USUVAL) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE,
  FOREIGN KEY (ID_VALORACION_USUVAL) REFERENCES VALORACIONES(ID_VAL) ON DELETE CASCADE
);

CREATE TABLE COMENTARIOS_USUARIOS(
  ID_COM_USU            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO_COMUSU     INT,
  ID_COMENTARIO_COMUSU  INT,
  ID_PUBLICACION_COMUSU INT,
  FOREIGN KEY (ID_USUARIO_COMUSU) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE,
  FOREIGN KEY (ID_COMENTARIO_COMUSU) REFERENCES COMENTARIO(ID_COM) ON DELETE CASCADE,   
  FOREIGN KEY (ID_PUBLICACION_COMUSU) REFERENCES PUBLICACIONES(ID_PUBLI) ON DELETE CASCADE
);

CREATE TABLE RECUPERAR_CONTRASEÑA (
  ID_REC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMAIL  VARCHAR(200) NOT NULL,
  TOKEN  VARCHAR(200) NOT NULL
);

CREATE TABLE COOKIE_SESION(
  ID_COO_SE         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COOKIE            VARCHAR(200) NOT NULL,
  ID_USUARIO_COOKIE INT NOT NULL ,
  FOREIGN KEY (ID_USUARIO_COOKIE) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE
);

CREATE TABLE PUBLICACION_FAVORITA(
  ID_PUB_FA          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_PUBLICACION_FAV INT,
  ID_USUARIO_FAV     INT,
  FOREIGN KEY (ID_PUBLICACION_FAV) REFERENCES PUBLICACIONES(ID_PUBLI) ON DELETE CASCADE,
  FOREIGN KEY (ID_USUARIO_FAV) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE
);

